// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://pxinbkhciqbndkshutii.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aW5ia2hjaXFibmRrc2h1dGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTE0OTksImV4cCI6MjA2ODQyNzQ5OX0._XKK1oEPkBLw4JBmSsK96KtufW9WFV1iNwCl_CFeNrw";

// Default schema: `public`
export const supabasePublic = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    db: { schema: 'public' },
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    db: { schema: 'duitkita' },
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);